/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RecargaRouteImport } from './routes/recarga'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCreatePixPaymentRouteImport } from './routes/api/public/create-pix-payment'
import { Route as ApiPublicCheckPixPaymentStatusRouteImport } from './routes/api/public/check-pix-payment-status'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RecargaRoute = RecargaRouteImport.update({
  id: '/recarga',
  path: '/recarga',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreatePixPaymentRoute =
  ApiPublicCreatePixPaymentRouteImport.update({
    id: '/api/public/create-pix-payment',
    path: '/api/public/create-pix-payment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCheckPixPaymentStatusRoute =
  ApiPublicCheckPixPaymentStatusRouteImport.update({
    id: '/api/public/check-pix-payment-status',
    path: '/api/public/check-pix-payment-status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/painel': typeof PainelRoute
  '/recarga': typeof RecargaRoute
  '/sobre': typeof SobreRoute
  '/api/public/check-pix-payment-status': typeof ApiPublicCheckPixPaymentStatusRoute
  '/api/public/create-pix-payment': typeof ApiPublicCreatePixPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/painel': typeof PainelRoute
  '/recarga': typeof RecargaRoute
  '/sobre': typeof SobreRoute
  '/api/public/check-pix-payment-status': typeof ApiPublicCheckPixPaymentStatusRoute
  '/api/public/create-pix-payment': typeof ApiPublicCreatePixPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/painel': typeof PainelRoute
  '/recarga': typeof RecargaRoute
  '/sobre': typeof SobreRoute
  '/api/public/check-pix-payment-status': typeof ApiPublicCheckPixPaymentStatusRoute
  '/api/public/create-pix-payment': typeof ApiPublicCreatePixPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/painel'
    | '/recarga'
    | '/sobre'
    | '/api/public/check-pix-payment-status'
    | '/api/public/create-pix-payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/painel'
    | '/recarga'
    | '/sobre'
    | '/api/public/check-pix-payment-status'
    | '/api/public/create-pix-payment'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/painel'
    | '/recarga'
    | '/sobre'
    | '/api/public/check-pix-payment-status'
    | '/api/public/create-pix-payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  PainelRoute: typeof PainelRoute
  RecargaRoute: typeof RecargaRoute
  SobreRoute: typeof SobreRoute
  ApiPublicCheckPixPaymentStatusRoute: typeof ApiPublicCheckPixPaymentStatusRoute
  ApiPublicCreatePixPaymentRoute: typeof ApiPublicCreatePixPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recarga': {
      id: '/recarga'
      path: '/recarga'
      fullPath: '/recarga'
      preLoaderRoute: typeof RecargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-pix-payment': {
      id: '/api/public/create-pix-payment'
      path: '/api/public/create-pix-payment'
      fullPath: '/api/public/create-pix-payment'
      preLoaderRoute: typeof ApiPublicCreatePixPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-pix-payment-status': {
      id: '/api/public/check-pix-payment-status'
      path: '/api/public/check-pix-payment-status'
      fullPath: '/api/public/check-pix-payment-status'
      preLoaderRoute: typeof ApiPublicCheckPixPaymentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  PainelRoute: PainelRoute,
  RecargaRoute: RecargaRoute,
  SobreRoute: SobreRoute,
  ApiPublicCheckPixPaymentStatusRoute: ApiPublicCheckPixPaymentStatusRoute,
  ApiPublicCreatePixPaymentRoute: ApiPublicCreatePixPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
